import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Big_Shoulders_Display } from 'next/font/google';
import "./styles/globals.css";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bigShoulders = Big_Shoulders_Display({
  subsets: ['latin'],
  weight: ['100', '400', '900'],
  display: 'swap',
  variable: '--font-big-shoulders',
});

export const metadata: Metadata = {
  title: "Tailwind Practise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="dark" className={bigShoulders.className} >
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
